name: Build Mixed Arch Image

env:
  VERSION: v3.3

on:
  pull_request:
    branches:
      - exc-*
  push:
    branches:
      - ecx-*

jobs:
  build-and-push-device-plugin:
    name: Build Mixed Arch Image
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_ORG }}/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Mixed Arch images
        run: make buildx-push
